# Generated by Django 2.2.12 on 2020-11-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='info',
            field=models.CharField(default='', max_length=150, verbose_name='个人简介'),
        ),
    ]
